version: "1"
nginx:
    image: nginx:latest
   volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
   ports:
      - "80:80"
      - "443:443"
   links:
      - service1:service1
      - service2:service2
   restart: always
fpm:
  build: ./php-fpm
  ports:
    - "9000"
  volumes:
    - ./app/src:/usr/share/nginx/html
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  links:
    - mysql:mysql
php:
    build: ./php
    ports:
        - "9009:9000"
    links:
        - mysql
#    volumes:
#        - ./php7/config/php.ini:/usr/local/php/lib/php.ini:ro
    restart: always
mysql:
    build: ./mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_DATABASE=mysql
        - MYSQL_USER=developer
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=123456
    volumes:
        - /opt/data/mysql:/var/lib/mysql
    restart: always